server:
  port: 9902

spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB #限制文件上传大小



eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}


fdfs:
  connect-timeout: 601 #连接超时时间
  so-timeout: 1501 #读取时间
  #缩略图
  thumb-image:
    width: 60
    height: 60
  #tracker服务器地址
  tracker-list:
    - 192.168.1.105:22122
    - 192.168.1.106:22122